/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const { evolve, reject } = require("ramda");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  openApiSidebar: [
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "Aquí encontrarás todos los endpoints con los que podrás consultar y manipular la información de nuestra plataforma.",
        slug: "/category/api",
      },
      // @ts-ignore
      items: require("./docs/api/sidebar.js")
        // Se ignoran controllers con tag private/loquesea
        .filter(
          (it) => !(it.type === "category" && it.label?.startsWith("private/"))
        )
        // Se ignoran endpoints que contengan [private] en su summary
        .map(
          evolve({
            items: reject((item) => item.label?.includes("[private]")),
          })
        ),
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
